<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<fmt:setLocale value="vi_VN" />
<c:if test="${empty sessionScope.user || sessionScope.user.role != 'admin'}"><c:redirect url="/login.jsp"/></c:if>
<c:set var="activePage" value="inventory"/><c:set var="pageTitle" value="Kho nguyên liệu"/>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Kho nguyên liệu – Sun Coffee</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Nunito:wght@400;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/admin-style.css"></head>
<body><div class="app-wrapper"><%@ include file="../components/header.jsp" %><%@ include file="../components/sidebar-admin.jsp" %><main class="main-content"><div class="page-header d-flex justify-between align-center flex-wrap gap-1"><div><h2>📦 Kho nguyên liệu</h2><p>Quản lý vật tư, nguyên liệu trong kho</p></div><button class="btn btn-primary" onclick="openModal('modal-add-item')">Thêm nguyên liệu</button></div>
<div class="stats-grid"><div class="stat-card"><div class="stat-icon">📦</div><div class="stat-value">${fn:length(items)}</div><div class="stat-label">Tổng nguyên liệu</div></div><div class="stat-card"><div class="stat-icon">⚠️</div><div class="stat-value">${lowStockCount}</div><div class="stat-label">Sắp hết</div></div></div>
<div class="filter-bar"><div class="search-box"><span class="search-icon">🔍</span><input class="search-input" placeholder="Tìm nguyên liệu..." oninput="searchAnyTable(this.value,'inventory-table')"></div></div>
<div class="card"><div class="card-header"><h3>Danh sách nguyên liệu</h3></div><div class="table-wrapper"><table class="data-table" id="inventory-table"><thead><tr><th>Nguyên liệu</th><th>Số lượng</th><th>Tối thiểu</th><th>Đơn vị</th><th>Nhà cung cấp</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><c:forEach var="item" items="${items}"><tr><td class="fw-bold">${item.itemName}</td><td>${item.quantity}</td><td>${item.minQuantity}</td><td>${item.unit}</td><td>${item.supplier}</td><td><c:choose><c:when test="${item.lowStock}"><span class="badge badge-warning">Sắp hết</span></c:when><c:when test="${item.status == 'active'}"><span class="badge badge-success">Đủ hàng</span></c:when><c:otherwise><span class="badge badge-danger">Ngừng dùng</span></c:otherwise></c:choose></td><td><div class="actions"><button class="btn btn-primary btn-sm js-adjust-stock" data-id="${item.id}" data-name="${fn:escapeXml(item.itemName)}" data-quantity="${item.quantity}">Tồn kho</button><button class="btn btn-ghost btn-sm js-edit-item" data-id="${item.id}" data-name="${fn:escapeXml(item.itemName)}" data-unit="${fn:escapeXml(item.unit)}" data-quantity="${item.quantity}" data-min="${item.minQuantity}" data-supplier="${fn:escapeXml(item.supplier)}" data-status="${item.status}">Sửa</button><form id="del-item-${item.id}" action="${pageContext.request.contextPath}/inventory" method="post" style="display:none"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="${item.id}"></form><button class="btn btn-danger btn-sm" onclick="confirmDelete('del-item-${item.id}','${fn:escapeXml(item.itemName)}')">Xóa</button></div></td></tr></c:forEach><c:if test="${empty items}"><tr><td colspan="7" class="empty-cell">Chưa có nguyên liệu</td></tr></c:if></tbody></table></div></div>
</main><%@ include file="../components/footer.jsp" %></div>
<div class="modal-overlay" id="modal-add-item" onclick="closeOnBackdrop(event,'modal-add-item')"><div class="modal-box"><div class="modal-header"><h3>Thêm nguyên liệu</h3><button class="modal-close" onclick="closeModal('modal-add-item')">✕</button></div><div class="modal-body"><form action="${pageContext.request.contextPath}/inventory" method="post"><input type="hidden" name="action" value="add"><%@ include file="inventory-form.jspf" %><div class="modal-footer"><button type="button" class="btn btn-ghost" onclick="closeModal('modal-add-item')">Hủy</button><button class="btn btn-primary">Lưu</button></div></form></div></div></div>
<div class="modal-overlay" id="modal-edit-item" onclick="closeOnBackdrop(event,'modal-edit-item')"><div class="modal-box"><div class="modal-header"><h3>Sửa nguyên liệu</h3><button class="modal-close" onclick="closeModal('modal-edit-item')">✕</button></div><div class="modal-body"><form id="form-edit-item" action="${pageContext.request.contextPath}/inventory" method="post"><input type="hidden" name="action" value="update"><input type="hidden" name="id"><%@ include file="inventory-form.jspf" %><div class="modal-footer"><button type="button" class="btn btn-ghost" onclick="closeModal('modal-edit-item')">Hủy</button><button class="btn btn-primary">Lưu thay đổi</button></div></form></div></div></div>
<div class="modal-overlay" id="modal-adjust-stock" onclick="closeOnBackdrop(event,'modal-adjust-stock')"><div class="modal-box"><div class="modal-header"><h3>Điều chỉnh tồn kho</h3><button class="modal-close" onclick="closeModal('modal-adjust-stock')">✕</button></div><div class="modal-body"><form id="form-adjust-stock" action="${pageContext.request.contextPath}/inventory" method="post"><input type="hidden" name="action" value="adjustStock"><input type="hidden" name="id"><div class="form-group"><label class="form-label">Tên nguyên liệu</label><input type="text" id="adjust-item-name" class="form-control" readonly style="background:var(--cream-2); border:none; font-weight:bold;"></div><div class="form-group"><label class="form-label">Số lượng hiện tại</label><input type="text" id="adjust-current-qty" class="form-control" readonly style="background:var(--cream-2); border:none; font-weight:bold;"></div><div class="form-group"><label class="form-label">Số lượng tồn kho mới <span class="required">*</span></label><input type="number" name="quantity" step="0.01" min="0" class="form-control" required placeholder="Nhập số lượng tồn thực tế"></div><div class="modal-footer"><button type="button" class="btn btn-ghost" onclick="closeModal('modal-adjust-stock')">Hủy</button><button type="submit" class="btn btn-primary">Lưu số lượng mới</button></div></form></div></div></div>
<script src="${pageContext.request.contextPath}/assets/js/admin-script.js" charset="UTF-8"></script></body></html>
